version: "2"
services:
  app:
    container_name: cronofy
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "3001:27017"